/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zkewed.weather.views;

/**
 *
 * @author DELL
 */
public class Splash extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;

    /**
     * Creates new form Splash
     */
    public Splash() {

        initComponents();
        setSize(600, 428);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(476, 544));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(loadText);
        loadText.setBounds(240, 280, 110, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/analytics (5).png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 320, 80, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/analytics (7).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 320, 80, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/analytics (8).png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 320, 80, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/analytics (2).png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 320, 70, 90);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 280, 260, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/analytics (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 320, 64, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 450, 240);

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zkewed/weather/photos/abstract-background-green-tones_1055-1856.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -20, 630, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);           // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();          // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel loadText;
    // End of variables declaration//GEN-END:variables

public void setLoad(int x){
    loadText.setText("Loading........."+Integer.toString(x)+"%");
}
}
